name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-with-depot:
    name: Build with Depot
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: depot/setup-action@v1

      - name: Composer
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY=astria-composer
          platforms: linux/amd64,linux/arm64
          project: p5v7137kpl

      - name: Conductor
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY=astria-conductor
          platforms: linux/amd64,linux/arm64
          project: cxfdwp8jw0

      - name: Sequencer
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY=astria-sequencer
          platforms: linux/amd64,linux/arm64
          project: mqggksr9rg

      - name: Sequencer-relayer
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY=astria-sequencer-relayer
          platforms: linux/amd64,linux/arm64
          project: fmqsd95w2h
