name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1

      - name: Composer
        uses: docker/build-push-action@v2
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-composer"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Conductor
        uses: docker/build-push-action@v2
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-conductor"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sequencer
        uses: docker/build-push-action@v2
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-sequencer"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sequencer-relayer
        uses: docker/build-push-action@v2
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-sequencer-relayer"
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-with-depot:
    name: Build with Depot
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: depot/setup-action@v1

      - name: Composer
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-composer"
          platforms: linux/amd64,linux/arm64
          project: p5v7137kpl

      - name: Conductor
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-conductor"
          platforms: linux/amd64,linux/arm64
          project: cxfdwp8jw0

      - name: Sequencer
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-sequencer"
          platforms: linux/amd64,linux/arm64
          project: mqggksr9rg

      - name: Sequencer-relayer
        uses: depot/build-push-action@v1
        with:
          context: ./upstream
          file: ./upstream/containerfiles/Dockerfile
          build-args: |
            TARGETBINARY="astria-sequencer-relayer"
          platforms: linux/amd64,linux/arm64
          project: fmqsd95w2h
